name: animated_toast_plus
description: A customizable and animated toast/snackbar package for Flutter.
version: 1.0.0
author: Md Mahmudul Hasan <swe.mahmud@gmail.com>
homepage: https://github.com/dev-mahmudulhasan/animated_toast_plus
repository: https://github.com/dev-mahmudulhasan/animated_toast_plus
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

